### ISSUE TITLE
Help is broken without product-versions.json

### ISSUE THREAD

**Issue by QuLogic** [juhp/fbrnch#10]
I mentioned on IRC that `product-versions.json` broke somehow, though I managed to fix it. This is not a report about that. Rather, it is a report that `--help`/`-h` broke while that file is missing.

Even if `product-versions.json` cannot be downloaded or is invalid, `--help` should never be broken. Command-line options should be checked before doing anything, just in case `--help` is requested.

**Comment by juhp** [comment]
Yeah I noticed this too while trying to build the package in copr (I ended up disabling the manpage, because I wanted to get the release out, but maybe I was too cavalier on this :-( ).

Actually I am not completely sure what is going on/wrong - the cached json file should expire every 6 years: seems like something could be wrong though in retrospect I realised I should have renamed the name along with the content change.

Let me try to massage it so that it doesn't happen.

**Comment by juhp** [comment]
Just for reference the json file should now be an array of the product versions.

**Comment by juhp** [comment]
Ah I found the actual problem: the cabal build (which I use for copr) was still using an older broken commit for the pdc lib - no wonder the parsing was breaking. :-(

**Comment by juhp** [comment]
> Ah I found the actual problem: the cabal build (which I use for copr) was still using an older broken commit for the pdc lib - no wonder it wasn't working. :-(

That should be fixed in fbrnch-0.4-2

**Comment by QuLogic** [comment]
Also, if the JSON is invalid, then tab complete doesn't work.

**Comment by juhp** [comment]
I have added some further changes in git on Sunday to further prevent this from re-occurring:
renamed the json file and also removed it's early parsing in main
(essentially removing the last clever ""skeumorphism"" from the option processing).

Thank you for reporting this bug.
